### ISSUE TITLE
How to use it in 4.26.2?

### ISSUE THREAD

**Issue by Viznity** [Cesio137/UE4-GraphicsRHIManager#1]
Hi! How can I use it in 4.26.2?

![image](https://user-images.githubusercontent.com/87879991/189772435-75a8653b-2b7c-4acf-a8d9-8231586c768c.png)

**Comment by nathancmiguel** [comment]
> Hi! How can I use it in 4.26.2?
> 
> ![image](https://user-images.githubusercontent.com/87879991/189772435-75a8653b-2b7c-4acf-a8d9-8231586c768c.png)
> 

You have to open VS first and then compile the project

**Comment by Viznity** [comment]
Hi! Project opened, but now I'm unable to package project.
![image](https://user-images.githubusercontent.com/87879991/189980378-10e4b836-cb21-4ee7-ba4c-5801e2bfd5e8.png)

**Comment by nathancmiguel** [comment]
https://github.com/Cesio137/GConfigManager

here with 4.26 support
